name: check
on:
  push:
    branches:
      - master
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@master
      - name: test
        run: |
          echo "Hello World!"
