name: rorw_dump
on:
  push:
    branches:
      - master
jobs:
  rodump:
    runs-on: ro
    steps:
      - name: output hostname
        run: hostname
  rwdump:
    runs-on: rw
    steps:
      - name: output hostname
        run: hostname
